dtb-$(CONFIG_ARCH_S5P6818) += s5p6818-nanopi3-rev01.dtb
dtb-$(CONFIG_ARCH_S5P6818) += s5p6818-nanopi3-rev02.dtb
dtb-$(CONFIG_ARCH_S5P6818) += s5p6818-nanopi3-rev03.dtb
dtb-$(CONFIG_ARCH_S5P6818) += s5p6818-nanopi3-rev05.dtb
dtb-$(CONFIG_ARCH_S5P6818) += s5p6818-nanopi3-rev07.dtb

ifeq ($(CONFIG_ARCH_S5P6818),y)
	DTC_FLAGS	?= -@ -H epapr
endif
